[package]
name = "lopi-py/rodux-hooks"
description = "React hooks for Rodux"
authors = ["Lopy"]
version = "0.2.13"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
license = "MIT"
include = ["wally.toml", "default.project.json", "src", "src/**"]
exclude = ["**"]

[dependencies]
React = "core-packages/react@17.0.1-rc.19"
